-- Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2020.2 (win64) Build 3064766 Wed Nov 18 09:12:45 MST 2020
-- Date        : Thu Aug 21 16:23:39 2025
-- Host        : AsusROG running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim {c:/Users/Taimoor/Desktop/SIVP
--               Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_sv_wrapper_read_buff_0_0/IP_MAC_BD_sv_wrapper_read_buff_0_0_sim_netlist.vhdl}
-- Design      : IP_MAC_BD_sv_wrapper_read_buff_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity IP_MAC_BD_sv_wrapper_read_buff_0_0 is
  port (
    clk : in STD_LOGIC;
    rst_n : in STD_LOGIC;
    rxd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_dv : in STD_LOGIC;
    rx_er : in STD_LOGIC;
    empty : in STD_LOGIC;
    ip_id : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ip_dst : out STD_LOGIC_VECTOR ( 31 downto 0 );
    tcp_src : out STD_LOGIC_VECTOR ( 15 downto 0 );
    tcp_dst : out STD_LOGIC_VECTOR ( 15 downto 0 );
    tcp_seq : out STD_LOGIC_VECTOR ( 31 downto 0 );
    tcp_ack : out STD_LOGIC_VECTOR ( 31 downto 0 );
    tcp_window : out STD_LOGIC_VECTOR ( 15 downto 0 );
    fields_valid : out STD_LOGIC;
    detected : out STD_LOGIC;
    pipe_rxd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    pipe_rx_dv : out STD_LOGIC;
    pipe_rx_er : out STD_LOGIC;
    pipe_empty : out STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of IP_MAC_BD_sv_wrapper_read_buff_0_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of IP_MAC_BD_sv_wrapper_read_buff_0_0 : entity is "IP_MAC_BD_sv_wrapper_read_buff_0_0,sv_wrapper_read_buffer,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of IP_MAC_BD_sv_wrapper_read_buff_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of IP_MAC_BD_sv_wrapper_read_buff_0_0 : entity is "module_ref";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of IP_MAC_BD_sv_wrapper_read_buff_0_0 : entity is "sv_wrapper_read_buffer,Vivado 2020.2";
end IP_MAC_BD_sv_wrapper_read_buff_0_0;

architecture STRUCTURE of IP_MAC_BD_sv_wrapper_read_buff_0_0 is
  signal \<const0>\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of clk : signal is "xilinx.com:signal:clock:1.0 clk CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of clk : signal is "XIL_INTERFACENAME clk, FREQ_HZ 2e+08, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN IP_MAC_BD_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of rst_n : signal is "xilinx.com:signal:reset:1.0 rst_n RST";
  attribute X_INTERFACE_PARAMETER of rst_n : signal is "XIL_INTERFACENAME rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
begin
  detected <= \<const0>\;
  fields_valid <= \<const0>\;
  ip_dst(31) <= \<const0>\;
  ip_dst(30) <= \<const0>\;
  ip_dst(29) <= \<const0>\;
  ip_dst(28) <= \<const0>\;
  ip_dst(27) <= \<const0>\;
  ip_dst(26) <= \<const0>\;
  ip_dst(25) <= \<const0>\;
  ip_dst(24) <= \<const0>\;
  ip_dst(23) <= \<const0>\;
  ip_dst(22) <= \<const0>\;
  ip_dst(21) <= \<const0>\;
  ip_dst(20) <= \<const0>\;
  ip_dst(19) <= \<const0>\;
  ip_dst(18) <= \<const0>\;
  ip_dst(17) <= \<const0>\;
  ip_dst(16) <= \<const0>\;
  ip_dst(15) <= \<const0>\;
  ip_dst(14) <= \<const0>\;
  ip_dst(13) <= \<const0>\;
  ip_dst(12) <= \<const0>\;
  ip_dst(11) <= \<const0>\;
  ip_dst(10) <= \<const0>\;
  ip_dst(9) <= \<const0>\;
  ip_dst(8) <= \<const0>\;
  ip_dst(7) <= \<const0>\;
  ip_dst(6) <= \<const0>\;
  ip_dst(5) <= \<const0>\;
  ip_dst(4) <= \<const0>\;
  ip_dst(3) <= \<const0>\;
  ip_dst(2) <= \<const0>\;
  ip_dst(1) <= \<const0>\;
  ip_dst(0) <= \<const0>\;
  ip_id(15) <= \<const0>\;
  ip_id(14) <= \<const0>\;
  ip_id(13) <= \<const0>\;
  ip_id(12) <= \<const0>\;
  ip_id(11) <= \<const0>\;
  ip_id(10) <= \<const0>\;
  ip_id(9) <= \<const0>\;
  ip_id(8) <= \<const0>\;
  ip_id(7) <= \<const0>\;
  ip_id(6) <= \<const0>\;
  ip_id(5) <= \<const0>\;
  ip_id(4) <= \<const0>\;
  ip_id(3) <= \<const0>\;
  ip_id(2) <= \<const0>\;
  ip_id(1) <= \<const0>\;
  ip_id(0) <= \<const0>\;
  pipe_empty <= \<const0>\;
  pipe_rx_dv <= \<const0>\;
  pipe_rx_er <= \<const0>\;
  pipe_rxd(7) <= \<const0>\;
  pipe_rxd(6) <= \<const0>\;
  pipe_rxd(5) <= \<const0>\;
  pipe_rxd(4) <= \<const0>\;
  pipe_rxd(3) <= \<const0>\;
  pipe_rxd(2) <= \<const0>\;
  pipe_rxd(1) <= \<const0>\;
  pipe_rxd(0) <= \<const0>\;
  tcp_ack(31) <= \<const0>\;
  tcp_ack(30) <= \<const0>\;
  tcp_ack(29) <= \<const0>\;
  tcp_ack(28) <= \<const0>\;
  tcp_ack(27) <= \<const0>\;
  tcp_ack(26) <= \<const0>\;
  tcp_ack(25) <= \<const0>\;
  tcp_ack(24) <= \<const0>\;
  tcp_ack(23) <= \<const0>\;
  tcp_ack(22) <= \<const0>\;
  tcp_ack(21) <= \<const0>\;
  tcp_ack(20) <= \<const0>\;
  tcp_ack(19) <= \<const0>\;
  tcp_ack(18) <= \<const0>\;
  tcp_ack(17) <= \<const0>\;
  tcp_ack(16) <= \<const0>\;
  tcp_ack(15) <= \<const0>\;
  tcp_ack(14) <= \<const0>\;
  tcp_ack(13) <= \<const0>\;
  tcp_ack(12) <= \<const0>\;
  tcp_ack(11) <= \<const0>\;
  tcp_ack(10) <= \<const0>\;
  tcp_ack(9) <= \<const0>\;
  tcp_ack(8) <= \<const0>\;
  tcp_ack(7) <= \<const0>\;
  tcp_ack(6) <= \<const0>\;
  tcp_ack(5) <= \<const0>\;
  tcp_ack(4) <= \<const0>\;
  tcp_ack(3) <= \<const0>\;
  tcp_ack(2) <= \<const0>\;
  tcp_ack(1) <= \<const0>\;
  tcp_ack(0) <= \<const0>\;
  tcp_dst(15) <= \<const0>\;
  tcp_dst(14) <= \<const0>\;
  tcp_dst(13) <= \<const0>\;
  tcp_dst(12) <= \<const0>\;
  tcp_dst(11) <= \<const0>\;
  tcp_dst(10) <= \<const0>\;
  tcp_dst(9) <= \<const0>\;
  tcp_dst(8) <= \<const0>\;
  tcp_dst(7) <= \<const0>\;
  tcp_dst(6) <= \<const0>\;
  tcp_dst(5) <= \<const0>\;
  tcp_dst(4) <= \<const0>\;
  tcp_dst(3) <= \<const0>\;
  tcp_dst(2) <= \<const0>\;
  tcp_dst(1) <= \<const0>\;
  tcp_dst(0) <= \<const0>\;
  tcp_seq(31) <= \<const0>\;
  tcp_seq(30) <= \<const0>\;
  tcp_seq(29) <= \<const0>\;
  tcp_seq(28) <= \<const0>\;
  tcp_seq(27) <= \<const0>\;
  tcp_seq(26) <= \<const0>\;
  tcp_seq(25) <= \<const0>\;
  tcp_seq(24) <= \<const0>\;
  tcp_seq(23) <= \<const0>\;
  tcp_seq(22) <= \<const0>\;
  tcp_seq(21) <= \<const0>\;
  tcp_seq(20) <= \<const0>\;
  tcp_seq(19) <= \<const0>\;
  tcp_seq(18) <= \<const0>\;
  tcp_seq(17) <= \<const0>\;
  tcp_seq(16) <= \<const0>\;
  tcp_seq(15) <= \<const0>\;
  tcp_seq(14) <= \<const0>\;
  tcp_seq(13) <= \<const0>\;
  tcp_seq(12) <= \<const0>\;
  tcp_seq(11) <= \<const0>\;
  tcp_seq(10) <= \<const0>\;
  tcp_seq(9) <= \<const0>\;
  tcp_seq(8) <= \<const0>\;
  tcp_seq(7) <= \<const0>\;
  tcp_seq(6) <= \<const0>\;
  tcp_seq(5) <= \<const0>\;
  tcp_seq(4) <= \<const0>\;
  tcp_seq(3) <= \<const0>\;
  tcp_seq(2) <= \<const0>\;
  tcp_seq(1) <= \<const0>\;
  tcp_seq(0) <= \<const0>\;
  tcp_src(15) <= \<const0>\;
  tcp_src(14) <= \<const0>\;
  tcp_src(13) <= \<const0>\;
  tcp_src(12) <= \<const0>\;
  tcp_src(11) <= \<const0>\;
  tcp_src(10) <= \<const0>\;
  tcp_src(9) <= \<const0>\;
  tcp_src(8) <= \<const0>\;
  tcp_src(7) <= \<const0>\;
  tcp_src(6) <= \<const0>\;
  tcp_src(5) <= \<const0>\;
  tcp_src(4) <= \<const0>\;
  tcp_src(3) <= \<const0>\;
  tcp_src(2) <= \<const0>\;
  tcp_src(1) <= \<const0>\;
  tcp_src(0) <= \<const0>\;
  tcp_window(15) <= \<const0>\;
  tcp_window(14) <= \<const0>\;
  tcp_window(13) <= \<const0>\;
  tcp_window(12) <= \<const0>\;
  tcp_window(11) <= \<const0>\;
  tcp_window(10) <= \<const0>\;
  tcp_window(9) <= \<const0>\;
  tcp_window(8) <= \<const0>\;
  tcp_window(7) <= \<const0>\;
  tcp_window(6) <= \<const0>\;
  tcp_window(5) <= \<const0>\;
  tcp_window(4) <= \<const0>\;
  tcp_window(3) <= \<const0>\;
  tcp_window(2) <= \<const0>\;
  tcp_window(1) <= \<const0>\;
  tcp_window(0) <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
end STRUCTURE;
