# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/IP_MAC_BD_ila_2_2.xci
# IP: The module: 'IP_MAC_BD_ila_2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/IP_MAC_BD_ila_2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/IP_MAC_BD_ila_2_2.xci
# IP: The module: 'IP_MAC_BD_ila_2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/IP_MAC_BD_ila_2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_ila_2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
