# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_auto_pc_0/IP_MAC_BD_auto_pc_0.xci
# IP: The module: 'IP_MAC_BD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_auto_pc_0/IP_MAC_BD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_auto_pc_0/IP_MAC_BD_auto_pc_0.xci
# IP: The module: 'IP_MAC_BD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_auto_pc_0/IP_MAC_BD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
