# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/IP_MAC_BD_axi_smc_0.xci
# IP: The module: 'IP_MAC_BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/bd_743d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_0/bd_743d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_2/bd_743d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_3/bd_743d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_4/bd_743d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_5/bd_743d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_6/bd_743d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_7/bd_743d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_8/bd_743d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_9/bd_743d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_10/bd_743d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_11/bd_743d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_12/bd_743d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_13/bd_743d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_14/bd_743d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_15/bd_743d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_16/bd_743d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_2/bd_743d_arsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_3/bd_743d_rsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_4/bd_743d_awsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_5/bd_743d_wsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_6/bd_743d_bsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_10/bd_743d_s01a2s_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_11/bd_743d_sarn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_12/bd_743d_srn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_13/bd_743d_m00s2a_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_14/bd_743d_m00arn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_15/bd_743d_m00rn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/IP_MAC_BD_axi_smc_0.xci
# IP: The module: 'IP_MAC_BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/bd_743d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_0/bd_743d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_2/bd_743d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_3/bd_743d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_4/bd_743d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_5/bd_743d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_6/bd_743d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_7/bd_743d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_8/bd_743d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_9/bd_743d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_10/bd_743d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_11/bd_743d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_12/bd_743d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_13/bd_743d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_14/bd_743d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_15/bd_743d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_16/bd_743d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_1/bd_743d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_2/bd_743d_arsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_3/bd_743d_rsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_4/bd_743d_awsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_5/bd_743d_wsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_6/bd_743d_bsw_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_10/bd_743d_s01a2s_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_11/bd_743d_sarn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_12/bd_743d_srn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_13/bd_743d_m00s2a_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_14/bd_743d_m00arn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/bd_0/ip/ip_15/bd_743d_m00rn_0_ooc.xdc

# XDC: c:/Users/Taimoor/Desktop/SIVP Lab/IP_MAC_FP/IP_MAC_FP.srcs/sources_1/bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IP_MAC_BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
