# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/IP_MAC_BD/IP_MAC_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD || ORIG_REF_NAME==IP_MAC_BD} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_processing_system7_0_0/IP_MAC_BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_processing_system7_0_0 || ORIG_REF_NAME==IP_MAC_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_axi_dma_0_0/IP_MAC_BD_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_axi_dma_0_0 || ORIG_REF_NAME==IP_MAC_BD_axi_dma_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_ps7_0_axi_periph_0/IP_MAC_BD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==IP_MAC_BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_rst_ps7_0_200M_0/IP_MAC_BD_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_rst_ps7_0_200M_0 || ORIG_REF_NAME==IP_MAC_BD_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_axi_smc_0/IP_MAC_BD_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_axi_smc_0 || ORIG_REF_NAME==IP_MAC_BD_axi_smc_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_axi_serializer_0_0/IP_MAC_BD_axi_serializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_axi_serializer_0_0 || ORIG_REF_NAME==IP_MAC_BD_axi_serializer_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_sv_wrapper_fp_top_0_0/IP_MAC_BD_sv_wrapper_fp_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_sv_wrapper_fp_top_0_0 || ORIG_REF_NAME==IP_MAC_BD_sv_wrapper_fp_top_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_sv_wrapper_read_buff_0_0/IP_MAC_BD_sv_wrapper_read_buff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_sv_wrapper_read_buff_0_0 || ORIG_REF_NAME==IP_MAC_BD_sv_wrapper_read_buff_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_ila_0_0/IP_MAC_BD_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_ila_0_0 || ORIG_REF_NAME==IP_MAC_BD_ila_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_ila_0_1/IP_MAC_BD_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_ila_0_1 || ORIG_REF_NAME==IP_MAC_BD_ila_0_1} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_fsm_ddr_polling_0_0/IP_MAC_BD_fsm_ddr_polling_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_fsm_ddr_polling_0_0 || ORIG_REF_NAME==IP_MAC_BD_fsm_ddr_polling_0_0} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_ila_2_2/IP_MAC_BD_ila_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_ila_2_2 || ORIG_REF_NAME==IP_MAC_BD_ila_2_2} -quiet] -quiet

# IP: bd/IP_MAC_BD/ip/IP_MAC_BD_auto_pc_0/IP_MAC_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP_MAC_BD_auto_pc_0 || ORIG_REF_NAME==IP_MAC_BD_auto_pc_0} -quiet] -quiet

# XDC: bd/IP_MAC_BD/IP_MAC_BD_ooc.xdc
